FROM java:8

RUN mkdir -p /images

ADD https://drive.google.com/uc?id=1Qtdg9Xf1Bn4xTbw_GOx3k9DacMORk0BR&export=download WEBAPP.zip

ADD https://drive.google.com/uc?authuser=0&id=1QxRj19U-d2dAWJaXNiY5LM_7ZTrpatjs&export=download /images/images.zip

RUN cd /images && unzip images.zip && cd .. && unzip WEBAPP.zip

ENTRYPOINT ["java","-jar","bibliothequeWebApp-1.0-RELEASE.war"]
