version: "3"
services: 
 
 db:
         build: ./BDD_PostgreSQL
         container_name: db_P7
         restart: always
         ports: 
          - "5496:5432"
         expose: 
          - "5496"
         environment: 
          POSTGRES_DB: P7_bibliothequeWS
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

 web-service:
         build: ./WS
         container_name: ws_P7
         ports:
          - "8181:8181"
         expose:
          - "8181" 
         depends_on: 
          - db
         environment: 
          SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/P7_bibliothequeWS

 web-app:
         build: ./webApp
         container_name: webApp_P7
         ports:
          - "8080:8080"
         depends_on:
          - web-service
         volumes:
          - "/i/Documents/openclassrooms formation/P7/images:/i/Documents/openclassrooms formation/P7/images"
         environment:
          BIBLIO_WS_ENDPOINT_URL: http://web-service:8181/biblioWS/biblioWS
          CHEMIN_IMAGE: /i/Documents/openclassrooms formation/P7/images

